// rpcgen extracts simple RPC methods from backend_impl.go into rpc_backend_gen.go,
// and rewrites backend_impl.go to keep only complex/non-generated methods.
//
// Usage: go run ./cmd/rpcgen/
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, "agent/backend_impl.go", nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse: %v\n", err)
		os.Exit(1)
	}

	// Methods that stay in backend_impl.go (not extracted)
	keepManual := map[string]bool{
		// Infrastructure
		"call": true, "callVoid": true,
		"Start": true, "Stop": true, "Close": true, "Run": true,
		"SendInbound": true, "Subscribe": true,
		"SetTUIControlHandler": true, "WireCallbacks": true,
		"SetChatRenameFn": true, "BindChat": true,
		"ConnState": true, "ServerURL": true, "IsRemote": true,
		"RegisterCoreTool": true, "RegisterTool": true,
		"IndexGlobalTools": true, "SetSandbox": true,
		"SetChannelReconfigureFn": true,
		// Complex RPC (non-standard body)
		"CallRPC":         true,
		"AddSubscription": true, "UpdateSubscription": true,
		"GetTokenState":       true,
		"GetSessionMessages":  true,
		"GetAgentSessionDump": true, "GetAgentSessionDumpByFullKey": true,
		"SetMaxContextTokens": true, // variadic
		// Web user management
		"CreateWebUser": true, "ListWebUsers": true,
		"DeleteWebUser": true, "DeleteChat": true, "RenameChat": true,
	}

	// Separate declarations into keep and extract
	var keepDecls []ast.Decl
	var extracted []string
	var genCode strings.Builder

	genCode.WriteString("// Code generated by cmd/rpcgen. DO NOT EDIT.\n")
	genCode.WriteString("// To regenerate: go run ./cmd/rpcgen/\n\n")
	genCode.WriteString("package agent\n\n")
	genCode.WriteString("import (\n")
	genCode.WriteString("\t\"context\"\n")
	genCode.WriteString("\t\"time\"\n\n")
	genCode.WriteString("\t\"xbot/config\"\n")
	genCode.WriteString("\tllm \"xbot/llm\"\n")
	genCode.WriteString("\t\"xbot/protocol\"\n")
	genCode.WriteString(")\n\n")
	genCode.WriteString("// ── Generated Backend RPC methods ──────────────────────────────────────────\n")
	genCode.WriteString("// Extracted from backend_impl.go. Do not modify — regenerate with rpcgen.\n\n")

	for _, decl := range node.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			keepDecls = append(keepDecls, decl)
			continue
		}
		if fn.Recv == nil || len(fn.Recv.List) == 0 {
			keepDecls = append(keepDecls, decl)
			continue
		}
		star, ok := fn.Recv.List[0].Type.(*ast.StarExpr)
		if !ok {
			keepDecls = append(keepDecls, decl)
			continue
		}
		id, ok := star.X.(*ast.Ident)
		if !ok || id.Name != "Backend" {
			keepDecls = append(keepDecls, decl)
			continue
		}

		if keepManual[fn.Name.Name] {
			keepDecls = append(keepDecls, decl)
			continue
		}

		// Extract this method to gen file
		extracted = append(extracted, fn.Name.Name)
		var buf strings.Builder
		if err := printer.Fprint(&buf, fset, fn); err != nil {
			fmt.Fprintf(os.Stderr, "print %s: %v\n", fn.Name.Name, err)
			continue
		}
		genCode.WriteString(buf.String())
		genCode.WriteString("\n\n")
	}

	if len(extracted) == 0 {
		fmt.Println("No methods to extract.")
		return
	}

	// Write gen file
	genCodeStr := genCode.String()
	// Remove unused "context" import if no method uses it
	if !strings.Contains(genCodeStr, "ctx context.Context") {
		genCodeStr = strings.Replace(genCodeStr, "import \"context\"\n\n", "", 1)
	}

	if err := os.WriteFile("agent/rpc_backend_gen.go", []byte(genCodeStr), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write gen: %v\n", err)
		os.Exit(1)
	}

	// Rewrite backend_impl.go with only kept declarations
	node.Decls = keepDecls
	var newBuf strings.Builder
	newBuf.WriteString("// Code generated by cmd/rpcgen. DO NOT EDIT — except for hand-written methods.\n")
	newBuf.WriteString("// This file contains only complex/non-generated Backend methods.\n")
	newBuf.WriteString("// Simple RPC methods are in rpc_backend_gen.go.\n\n")
	if err := printer.Fprint(&newBuf, fset, node); err != nil {
		fmt.Fprintf(os.Stderr, "rewrite: %v\n", err)
		os.Exit(1)
	}

	// Clean up: remove duplicate header comments
	result := newBuf.String()
	// go/printer adds the original file comments; remove "Code generated" prefix duplication
	lines := strings.Split(result, "\n")
	var cleaned []string
	skipDup := false
	for i, line := range lines {
		if strings.HasPrefix(line, "// Code generated by cmd/rpcgen") && i < 5 {
			skipDup = true
			continue
		}
		if skipDup && (line == "" || strings.HasPrefix(line, "//")) {
			continue
		}
		skipDup = false
		cleaned = append(cleaned, line)
	}
	result = strings.Join(cleaned, "\n")

	// Re-add our header
	result = "// Backend implementation — hand-written methods only.\n" +
		"// Simple RPC methods are auto-generated in rpc_backend_gen.go.\n" +
		"// To regenerate: go run ./cmd/rpcgen/\n\n" +
		result

	if err := os.WriteFile("agent/backend_impl.go", []byte(result), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "rewrite backend_impl: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Extracted %d methods to agent/rpc_backend_gen.go:\n", len(extracted))
	for _, m := range extracted {
		fmt.Printf("  - %s\n", m)
	}
	fmt.Printf("Rewrote agent/backend_impl.go with %d remaining declarations.\n", len(keepDecls))
}
