/**
 * SettingsAccountLinking — cross-channel account linking panel.
 *
 * Users can generate a link code (to be consumed from CLI/Feishu) or
 * consume a link code generated by another channel.
 *
 * Backend APIs:
 *   POST /api/account/link-code  → {code, expires_in}
 *   POST /api/account/link       → {action, user_id, preview?}
 *   GET  /api/account/identities → {user_id, identities[]}
 */
import { useState, useEffect, useCallback } from 'react'
import { Link2, Copy, Check, AlertCircle, Loader2, Trash2 } from 'lucide-react'

import { SettingsSection } from './SettingsSection'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'
import { postAPI } from '@/lib/api'

interface IdentityEntry {
  id: number
  user_id: number
  channel: string
  channel_user_id: string
  linked_at: string
}

type Status = 'idle' | 'loading' | 'success' | 'error'

export function SettingsAccountLinking() {
  const [identities, setIdentities] = useState<IdentityEntry[]>([])
  const [identitiesLoading, setIdentitiesLoading] = useState(true)

  // Generate code state
  const [generatedCode, setGeneratedCode] = useState('')
  const [genStatus, setGenStatus] = useState<Status>('idle')
  const [copied, setCopied] = useState(false)

  // Consume code state
  const [inputCode, setInputCode] = useState('')
  const [linkStatus, setLinkStatus] = useState<Status>('idle')
  const [linkMessage, setLinkMessage] = useState('')

  const fetchIdentities = useCallback(async () => {
    setIdentitiesLoading(true)
    try {
      const data = await postAPI<{ identities?: IdentityEntry[] }>('/api/account/identities/list')
      setIdentities(data.identities || [])
    } catch {
      // ignore
    } finally {
      setIdentitiesLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchIdentities()
  }, [fetchIdentities])

  const handleGenerate = async () => {
    setGenStatus('loading')
    setGeneratedCode('')
    try {
      const data = await postAPI<{ code: string }>('/api/account/link-code')
      setGeneratedCode(data.code)
      setGenStatus('success')
      setCopied(false)
    } catch (err) {
      setGenStatus('error')
      setGeneratedCode(err instanceof Error ? err.message : 'Failed')
    }
  }

  const handleCopy = async () => {
    if (!generatedCode) return
    await navigator.clipboard.writeText(generatedCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleLink = async () => {
    if (!inputCode.trim()) return
    setLinkStatus('loading')
    setLinkMessage('')
    try {
      const data = await postAPI<{ action?: string; user_id?: number; message?: string }>(
        '/api/account/link',
        { code: inputCode.trim(), confirm: false },
      )
      if (data.action === 'merge_required') {
        // Auto-confirm merge
        const data2 = await postAPI<{ user_id?: number }>('/api/account/link', {
          code: inputCode.trim(),
          confirm: true,
        })
        setLinkStatus('success')
        setLinkMessage(`账号合并成功 (user_id: ${data2.user_id})`)
        fetchIdentities()
        setInputCode('')
      } else if (data.action === 'linked') {
        setLinkStatus('success')
        setLinkMessage(`关联成功 (user_id: ${data.user_id})`)
        fetchIdentities()
        setInputCode('')
      } else if (data.action === 'noop') {
        setLinkStatus('success')
        setLinkMessage('已关联，无需重复操作')
      } else {
        setLinkStatus('success')
        setLinkMessage(data.message || '操作成功')
        fetchIdentities()
      }
    } catch (err) {
      setLinkStatus('error')
      setLinkMessage(err instanceof Error ? err.message : '操作失败')
    }
  }

  const handleUnlink = async (identityId: number) => {
    try {
      await postAPI(`/api/account/identities/${identityId}/delete`)
      void fetchIdentities()
    } catch {
      // ignore
    }
  }

  const channelLabel = (ch: string) => {
    const labels: Record<string, string> = {
      cli: 'CLI',
      web: 'Web',
      feishu: '飞书',
      qq: 'QQ',
      napcat: 'NapCat',
      system: '系统',
    }
    return labels[ch] || ch
  }

  return (
    <div className="flex flex-col gap-2.5 p-4">
      {/* Generate link code */}
      <SettingsSection title="生成关联码" description="生成一个一次性关联码，在其他渠道（CLI / 飞书）输入此码完成关联。有效期 5 分钟。">
        <div className="flex flex-col gap-2">
          <Button
            onClick={handleGenerate}
            disabled={genStatus === 'loading'}
            variant="outline"
            size="sm"
            className="w-fit gap-2"
          >
            {genStatus === 'loading' ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Link2 className="size-4" />
            )}
            生成关联码
          </Button>
          {generatedCode && genStatus === 'success' && (
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2.5 rounded-lg border border-white/[.08] bg-white/[.03] px-3 py-2">
                <code className="flex-1 font-mono text-base font-semibold tracking-wider text-text-primary">
                  {generatedCode}
                </code>
                <Button
                  onClick={handleCopy}
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 p-0 hover:bg-white/[.1]"
                >
                  {copied ? (
                    <Check className="size-4 text-[#22c55e]" />
                  ) : (
                    <Copy className="size-4" />
                  )}
                </Button>
              </div>
              <p className="text-xs text-text-muted">
                请在需要关联的渠道执行以下命令（5 分钟内有效）：
              </p>
              <div className="flex flex-col gap-2.5">
                {/* CLI command */}
                <div className="flex items-center gap-2.5 rounded-lg border border-white/[.08] bg-white/[.03] px-2.5 py-2">
                  <span className="rounded bg-[#6c8cff]/14 px-1.5 py-0.5 text-[10px] font-medium text-[#6c8cff]">CLI</span>
                  <code className="flex-1 font-mono text-xs text-text-primary">
                    /link-account {generatedCode}
                  </code>
                  <Button
                    onClick={() => navigator.clipboard.writeText(`/link-account ${generatedCode}`)}
                    variant="ghost"
                    size="sm"
                    className="h-6 w-6 p-0 hover:bg-white/[.1]"
                  >
                    <Copy className="size-3" />
                  </Button>
                </div>
                {/* Feishu command */}
                <div className="flex items-center gap-2.5 rounded-lg border border-white/[.08] bg-white/[.03] px-2.5 py-2">
                  <span className="rounded bg-[#6c8cff]/14 px-1.5 py-0.5 text-[10px] font-medium text-[#6c8cff]">飞书</span>
                  <code className="flex-1 font-mono text-xs text-text-primary">
                    /link {generatedCode}
                  </code>
                  <Button
                    onClick={() => navigator.clipboard.writeText(`/link ${generatedCode}`)}
                    variant="ghost"
                    size="sm"
                    className="h-6 w-6 p-0 hover:bg-white/[.1]"
                  >
                    <Copy className="size-3" />
                  </Button>
                </div>
                {/* Web consume hint */}
                <div className="flex items-center gap-2.5 rounded-lg border border-white/[.08] bg-white/[.03] px-2.5 py-2">
                  <span className="rounded bg-[#6c8cff]/14 px-1.5 py-0.5 text-[10px] font-medium text-[#6c8cff]">Web</span>
                  <code className="flex-1 font-mono text-xs text-text-muted">
                    在上方「关联其他渠道」输入此码
                  </code>
                </div>
              </div>
            </div>
          )}
          {genStatus === 'error' && (
            <p className="flex items-center gap-1.5 text-xs text-[var(--status-error,#ef4444)]">
              <AlertCircle className="size-3.5" />
              {generatedCode}
            </p>
          )}
        </div>
      </SettingsSection>

      {/* Consume link code */}
      <SettingsSection title="关联其他渠道" description="输入在其他渠道生成的关联码，将当前账号与该渠道关联。">
        <div className="flex flex-col gap-2.5">
          <div className="flex gap-2.5">
            <Input
              value={inputCode}
              onChange={(e) => setInputCode(e.target.value)}
              placeholder="输入关联码..."
              className="rounded-lg border-white/[.08] bg-white/[.03] font-mono focus-visible:border-[#6c8cff]/40 focus-visible:ring-[#6c8cff]/25"
              onKeyDown={(e) => {
                if (e.key === 'Enter' && inputCode.trim()) {
                  handleLink()
                }
              }}
            />
            <Button
              onClick={handleLink}
              disabled={linkStatus === 'loading' || !inputCode.trim()}
              size="sm"
              className="gap-2 bg-[#6c8cff]/14 text-[#6c8cff] hover:bg-[#6c8cff]/25"
            >
              {linkStatus === 'loading' ? (
                <Loader2 className="size-4 animate-spin" />
              ) : (
                <Link2 className="size-4" />
              )}
              关联
            </Button>
          </div>
          {linkMessage && (
            <p
              className={cn(
                'flex items-center gap-1.5 text-xs',
                linkStatus === 'error' ? 'text-[var(--status-error,#ef4444)]' : 'text-[#22c55e]',
              )}
            >
              <AlertCircle className="size-3.5" />
              {linkMessage}
            </p>
          )}
        </div>
      </SettingsSection>

      {/* Linked identities */}
      <SettingsSection title="已关联的身份" description="当前账号关联的所有渠道身份。解除关联不会丢失已迁移的资产。">
        <div className="flex flex-col gap-2.5">
          {identitiesLoading ? (
            <div className="flex items-center gap-2 text-xs text-text-muted">
              <Loader2 className="size-3.5 animate-spin" />
              加载中...
            </div>
          ) : identities.length === 0 ? (
            <p className="text-xs text-text-muted">暂无关联身份</p>
          ) : (
            identities.map((id) => (
              <div
                key={id.id}
                className="flex items-center gap-2.5 rounded-lg border border-white/[.08] bg-white/[.02] px-3 py-2 transition-colors hover:bg-white/[.04]"
              >
                <span className="rounded bg-[#6c8cff]/14 px-1.5 py-0.5 text-xs font-medium text-[#6c8cff]">
                  {channelLabel(id.channel)}
                </span>
                <code className="flex-1 truncate font-mono text-xs text-text-muted">
                  {id.channel_user_id}
                </code>
                <span className="text-xs text-text-muted">
                  {id.linked_at ? new Date(id.linked_at).toLocaleDateString() : ''}
                </span>
                <Button
                  onClick={() => handleUnlink(id.id)}
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 p-0 text-text-muted hover:bg-white/[.1] hover:text-[var(--status-error,#ef4444)]"
                >
                  <Trash2 className="size-3.5" />
                </Button>
              </div>
            ))
          )}
        </div>
      </SettingsSection>
    </div>
  )
}
