/**
 * SettingsAccountLinking — cross-channel account linking panel.
 *
 * Users can generate a link code (to be consumed from CLI/Feishu) or
 * consume a link code generated by another channel.
 *
 * Backend APIs:
 *   POST /api/account/link-code  → {code, expires_in}
 *   POST /api/account/link       → {action, user_id, preview?}
 *   GET  /api/account/identities → {user_id, identities[]}
 */
import { useState, useEffect, useCallback } from 'react'
import { Link2, Copy, Check, AlertCircle, Loader2, Trash2 } from 'lucide-react'

import { SettingsSection } from './SettingsSection'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { cn } from '@/lib/utils'

interface IdentityEntry {
  id: number
  user_id: number
  channel: string
  channel_user_id: string
  linked_at: string
}

type Status = 'idle' | 'loading' | 'success' | 'error'

export function SettingsAccountLinking() {
  const [identities, setIdentities] = useState<IdentityEntry[]>([])
  const [identitiesLoading, setIdentitiesLoading] = useState(true)

  // Generate code state
  const [generatedCode, setGeneratedCode] = useState('')
  const [genStatus, setGenStatus] = useState<Status>('idle')
  const [copied, setCopied] = useState(false)

  // Consume code state
  const [inputCode, setInputCode] = useState('')
  const [linkStatus, setLinkStatus] = useState<Status>('idle')
  const [linkMessage, setLinkMessage] = useState('')

  const fetchIdentities = useCallback(async () => {
    setIdentitiesLoading(true)
    try {
      const res = await fetch('/api/account/identities')
      if (!res.ok) return
      const data = await res.json()
      setIdentities(data.identities || [])
    } catch {
      // ignore
    } finally {
      setIdentitiesLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchIdentities()
  }, [fetchIdentities])

  const handleGenerate = async () => {
    setGenStatus('loading')
    setGeneratedCode('')
    try {
      const res = await fetch('/api/account/link-code', { method: 'POST' })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        throw new Error(data.error || data.message || 'Failed')
      }
      const data = await res.json()
      setGeneratedCode(data.code)
      setGenStatus('success')
      setCopied(false)
    } catch (err) {
      setGenStatus('error')
      setGeneratedCode(err instanceof Error ? err.message : 'Failed')
    }
  }

  const handleCopy = async () => {
    if (!generatedCode) return
    await navigator.clipboard.writeText(generatedCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleLink = async () => {
    if (!inputCode.trim()) return
    setLinkStatus('loading')
    setLinkMessage('')
    try {
      const res = await fetch('/api/account/link', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: inputCode.trim(), confirm: false }),
      })
      const data = await res.json()
      if (!res.ok) {
        throw new Error(data.error || data.message || 'Failed')
      }
      if (data.action === 'merge_required') {
        // Auto-confirm merge
        const res2 = await fetch('/api/account/link', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ code: inputCode.trim(), confirm: true }),
        })
        const data2 = await res2.json()
        if (!res2.ok) {
          throw new Error(data2.error || data2.message || 'Merge failed')
        }
        setLinkStatus('success')
        setLinkMessage(`账号合并成功 (user_id: ${data2.user_id})`)
        fetchIdentities()
        setInputCode('')
      } else if (data.action === 'linked') {
        setLinkStatus('success')
        setLinkMessage(`关联成功 (user_id: ${data.user_id})`)
        fetchIdentities()
        setInputCode('')
      } else if (data.action === 'noop') {
        setLinkStatus('success')
        setLinkMessage('已关联，无需重复操作')
      } else {
        setLinkStatus('success')
        setLinkMessage(data.message || '操作成功')
        fetchIdentities()
      }
    } catch (err) {
      setLinkStatus('error')
      setLinkMessage(err instanceof Error ? err.message : '操作失败')
    }
  }

  const handleUnlink = async (identityId: number) => {
    try {
      await fetch(`/api/account/identities/${identityId}`, { method: 'DELETE' })
      fetchIdentities()
    } catch {
      // ignore
    }
  }

  const channelLabel = (ch: string) => {
    const labels: Record<string, string> = {
      cli: 'CLI',
      web: 'Web',
      feishu: '飞书',
      qq: 'QQ',
      napcat: 'NapCat',
      system: '系统',
    }
    return labels[ch] || ch
  }

  return (
    <div className="flex flex-col">
      {/* Generate link code */}
      <SettingsSection title="生成关联码" description="生成一个一次性关联码，在其他渠道（CLI / 飞书）输入此码完成关联。有效期 5 分钟。">
        <div className="flex flex-col gap-2">
          <Button
            onClick={handleGenerate}
            disabled={genStatus === 'loading'}
            variant="outline"
            size="sm"
            className="w-fit gap-2"
          >
            {genStatus === 'loading' ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <Link2 className="size-4" />
            )}
            生成关联码
          </Button>
          {generatedCode && genStatus === 'success' && (
            <div className="flex flex-col gap-2">
              <div className="flex items-center gap-2 rounded-lg border border-border bg-bg-secondary px-3 py-2">
                <code className="flex-1 font-mono text-base font-semibold tracking-wider text-foreground">
                  {generatedCode}
                </code>
                <Button
                  onClick={handleCopy}
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 p-0"
                >
                  {copied ? (
                    <Check className="size-4 text-green-500" />
                  ) : (
                    <Copy className="size-4" />
                  )}
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                请在需要关联的渠道执行以下命令（5 分钟内有效）：
              </p>
              <div className="flex flex-col gap-1.5">
                {/* CLI command */}
                <div className="flex items-center gap-2 rounded-md border border-border bg-bg-secondary px-2.5 py-1.5">
                  <span className="rounded bg-accent/15 px-1.5 py-0.5 text-[10px] font-medium text-foreground">CLI</span>
                  <code className="flex-1 font-mono text-xs text-foreground">
                    /link-account {generatedCode}
                  </code>
                  <Button
                    onClick={() => navigator.clipboard.writeText(`/link-account ${generatedCode}`)}
                    variant="ghost"
                    size="sm"
                    className="h-6 w-6 p-0"
                  >
                    <Copy className="size-3" />
                  </Button>
                </div>
                {/* Feishu command */}
                <div className="flex items-center gap-2 rounded-md border border-border bg-bg-secondary px-2.5 py-1.5">
                  <span className="rounded bg-accent/15 px-1.5 py-0.5 text-[10px] font-medium text-foreground">飞书</span>
                  <code className="flex-1 font-mono text-xs text-foreground">
                    /link {generatedCode}
                  </code>
                  <Button
                    onClick={() => navigator.clipboard.writeText(`/link ${generatedCode}`)}
                    variant="ghost"
                    size="sm"
                    className="h-6 w-6 p-0"
                  >
                    <Copy className="size-3" />
                  </Button>
                </div>
                {/* Web consume hint */}
                <div className="flex items-center gap-2 rounded-md border border-border bg-bg-secondary px-2.5 py-1.5">
                  <span className="rounded bg-accent/15 px-1.5 py-0.5 text-[10px] font-medium text-foreground">Web</span>
                  <code className="flex-1 font-mono text-xs text-muted-foreground">
                    在上方「关联其他渠道」输入此码
                  </code>
                </div>
              </div>
            </div>
          )}
          {genStatus === 'error' && (
            <p className="flex items-center gap-1.5 text-xs text-red-500">
              <AlertCircle className="size-3.5" />
              {generatedCode}
            </p>
          )}
        </div>
      </SettingsSection>

      {/* Consume link code */}
      <SettingsSection title="关联其他渠道" description="输入在其他渠道生成的关联码，将当前账号与该渠道关联。">
        <div className="flex flex-col gap-2">
          <div className="flex gap-2">
            <Input
              value={inputCode}
              onChange={(e) => setInputCode(e.target.value)}
              placeholder="输入关联码..."
              className="font-mono"
              onKeyDown={(e) => {
                if (e.key === 'Enter' && inputCode.trim()) {
                  handleLink()
                }
              }}
            />
            <Button
              onClick={handleLink}
              disabled={linkStatus === 'loading' || !inputCode.trim()}
              size="sm"
              className="gap-2"
            >
              {linkStatus === 'loading' ? (
                <Loader2 className="size-4 animate-spin" />
              ) : (
                <Link2 className="size-4" />
              )}
              关联
            </Button>
          </div>
          {linkMessage && (
            <p
              className={cn(
                'flex items-center gap-1.5 text-xs',
                linkStatus === 'error' ? 'text-red-500' : 'text-green-500',
              )}
            >
              <AlertCircle className="size-3.5" />
              {linkMessage}
            </p>
          )}
        </div>
      </SettingsSection>

      {/* Linked identities */}
      <SettingsSection title="已关联的身份" description="当前账号关联的所有渠道身份。解除关联不会丢失已迁移的资产。">
        <div className="flex flex-col gap-1.5">
          {identitiesLoading ? (
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <Loader2 className="size-3.5 animate-spin" />
              加载中...
            </div>
          ) : identities.length === 0 ? (
            <p className="text-xs text-muted-foreground">暂无关联身份</p>
          ) : (
            identities.map((id) => (
              <div
                key={id.id}
                className="flex items-center gap-2 rounded-lg border border-border px-3 py-2"
              >
                <span className="rounded bg-accent/15 px-1.5 py-0.5 text-xs font-medium text-foreground">
                  {channelLabel(id.channel)}
                </span>
                <code className="flex-1 truncate font-mono text-xs text-muted-foreground">
                  {id.channel_user_id}
                </code>
                <span className="text-xs text-muted-foreground">
                  {id.linked_at ? new Date(id.linked_at).toLocaleDateString() : ''}
                </span>
                <Button
                  onClick={() => handleUnlink(id.id)}
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 p-0 text-muted-foreground hover:text-red-500"
                >
                  <Trash2 className="size-3.5" />
                </Button>
              </div>
            ))
          )}
        </div>
      </SettingsSection>
    </div>
  )
}
