package agent

import (
	"context"
	"sort"
	"sync"

	"xbot/llm"
	log "xbot/logger"
)

// MessageContext is the context processed by middleware, carrying all information needed for message building.
// Middleware participates in the message building process by reading/modifying this structure.
type MessageContext struct {
	// Ctx standard context, for timeout control and cancellation
	Ctx context.Context

	// SystemParts system prompt parts, stored by key.
	// Eventually concatenated into a complete system message after sorting by key.
	// Uses map instead of string concatenation, making it easy for middleware to independently modify its own parts.
	SystemParts map[string]string

	// UserContent original user message content
	UserContent string

	// UserMessage 最终Send给 LLM 的用户消息（中间件可修改）
	UserMessage string

	// History conversation history
	History []llm.ChatMessage

	// Messages final constructed message list.
	// Usually assembled by pipeline at the end; middleware generally doesn't operate on it directly.
	Messages []llm.ChatMessage

	// --- Metadata possibly needed by middleware below ---

	// Channel message channel (e.g. feishu)
	Channel string

	// WorkDir Working directory（展示给 LLM 的路径）
	WorkDir string

	// CWD 当前Working directory（Agent 运行时的 cwd，可能与 WorkDir 不同）
	CWD string

	// SenderName Send者名称
	SenderName string

	// SenderID Send者 ID
	SenderID string

	// ChatID session ID
	ChatID string

	// Extra extension fields, middleware can pass custom data through this map
	Extra map[string]any
}

// Well-known Extra keys used by built-in middlewares.
// Use these constants instead of raw strings to avoid typos.
const (
	ExtraKeySkillsCatalog  = "skills_catalog"
	ExtraKeyAgentsCatalog  = "agents_catalog"
	ExtraKeyMemoryProvider = "memory_provider"
	ExtraKeyTenantID       = "tenant_id"
	ExtraKeyUserLanguage   = "user_language"
	ExtraKeyPermUsers      = "perm_users" // permission control user config
)

// GetExtra gets a value of specified type from Extra
func (mc *MessageContext) GetExtra(key string) (any, bool) {
	if mc.Extra == nil {
		return nil, false
	}
	v, ok := mc.Extra[key]
	return v, ok
}

// SetExtra sets a value in Extra
func (mc *MessageContext) SetExtra(key string, value any) {
	if mc.Extra == nil {
		mc.Extra = make(map[string]any)
	}
	mc.Extra[key] = value
}

// GetExtraString gets a string value from Extra
func (mc *MessageContext) GetExtraString(key string) (string, bool) {
	v, ok := mc.GetExtra(key)
	if !ok {
		return "", false
	}
	s, ok := v.(string)
	return s, ok
}

// GetExtraTyped gets a value of specified type T from Extra (generic helper).
// Avoids boilerplate of manual GetExtra + type assertion.
//
//	mem, ok := GetExtraTyped[memory.MemoryProvider](mc, ExtraKeyMemoryProvider)
func GetExtraTyped[T any](mc *MessageContext, key string) (T, bool) {
	v, ok := mc.GetExtra(key)
	if !ok {
		var zero T
		return zero, false
	}
	typed, ok := v.(T)
	return typed, ok
}

// BuildSystemPrompt concatenates SystemParts into a complete system prompt after sorting by key.
// Key naming convention determines concatenation order (lexicographic), recommended to use numeric prefixes:
//
//	"00_base"    - Base prompt template
//	"10_skills"  - Skills directory
//	"15_agents"  - Agents catalog
//	"20_memory"  - Memory内容
//	"30_sender"  - Send者信息
//	"90_time"    - Timestamp (changes most frequently, put last to optimize KV-cache)
func (mc *MessageContext) BuildSystemPrompt() string {
	if len(mc.SystemParts) == 0 {
		return ""
	}

	keys := make([]string, 0, len(mc.SystemParts))
	for k := range mc.SystemParts {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var total int
	for _, k := range keys {
		total += len(mc.SystemParts[k])
	}
	// pre-allocate: total content + newlines between parts
	buf := make([]byte, 0, total+len(keys))
	for i, k := range keys {
		if mc.SystemParts[k] == "" {
			continue
		}
		if i > 0 && len(buf) > 0 {
			buf = append(buf, '\n')
		}
		buf = append(buf, mc.SystemParts[k]...)
	}
	return string(buf)
}

// Assemble assembles the final message list.
// Assembles system prompt + history + user message into []ChatMessage.
func (mc *MessageContext) Assemble() []llm.ChatMessage {
	systemPrompt := mc.BuildSystemPrompt()

	messages := make([]llm.ChatMessage, 0, len(mc.History)+2)
	sysMsg := llm.NewSystemMessage(systemPrompt)
	sysMsg.CacheHint = "static"
	messages = append(messages, sysMsg)
	messages = append(messages, mc.History...)
	messages = append(messages, llm.NewUserMessage(mc.UserMessage))

	// assert: there can only be one system message (generated by this pipeline), history must not contain system (session doesn't persist system)
	var systemCount int
	for _, m := range messages {
		if m.Role == "system" {
			systemCount++
		}
	}
	if systemCount != 1 {
		// R-02 fix: panic changed to safe degradation, remove extra system messages, keep only the first
		log.WithField("system_count", systemCount).Error("assert: Assemble should produce exactly one system message (history may contain system)")
		// Safe degradation: remove extra system messages, keep only the first
		filtered := make([]llm.ChatMessage, 0, len(messages))
		seen := false
		for _, m := range messages {
			if m.Role == "system" {
				if !seen {
					filtered = append(filtered, m)
					seen = true
				}
				continue
			}
			filtered = append(filtered, m)
		}
		messages = filtered
	}
	mc.Messages = messages
	return messages
}

// MessageMiddleware message building middleware interface.
// Each middleware is responsible for an independent step in the message building process.
type MessageMiddleware interface {
	// Name returns middleware name, for logging and debugging
	Name() string

	// Priority returns middleware priority. Lower values execute first.
	// Recommended ranges:
	//   0-99:   Infrastructure (prompt templates, environment info)
	//   100-199: Context injection (skills, agents, memory)
	//   200-299: 用户Message processing（时间戳、Send者标识）
	//   300-399: Post-processing (token trimming, formatting)
	Priority() int

	// Process processes the message context.
	// Middleware should only modify its own part, don't overwrite other middleware's output.
	// When returning error, pipeline logs but continues execution (doesn't interrupt flow).
	Process(mc *MessageContext) error
}

// MessagePipeline message build pipeline, executes middleware chain by priority.
// Concurrency-safe: Agent holds a single pipeline instance, multiple goroutines can call Run() simultaneously.
// Use/Remove are write operations (usually called during initialization), Run/Middlewares are read operations.
type MessagePipeline struct {
	mu          sync.RWMutex
	middlewares []MessageMiddleware
	sorted      bool
}

// NewMessagePipeline creates message build pipeline
func NewMessagePipeline(middlewares ...MessageMiddleware) *MessagePipeline {
	p := &MessagePipeline{
		middlewares: middlewares,
	}
	p.sortLocked()
	return p
}

// Use adds middleware to the pipeline
func (p *MessagePipeline) Use(mw ...MessageMiddleware) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.middlewares = append(p.middlewares, mw...)
	p.sortLocked()
}

// Remove removes all middleware with the same name. Returns actual count removed.
func (p *MessagePipeline) Remove(name string) int {
	p.mu.Lock()
	defer p.mu.Unlock()
	n := 0
	filtered := p.middlewares[:0]
	for _, mw := range p.middlewares {
		if mw.Name() == name {
			n++
		} else {
			filtered = append(filtered, mw)
		}
	}
	p.middlewares = filtered
	return n
}

// sortLocked sorts middleware by priority (stable sort, same priority preserves insertion order).
// Caller must hold lock (mu.Lock).
func (p *MessagePipeline) sortLocked() {
	sort.SliceStable(p.middlewares, func(i, j int) bool {
		return p.middlewares[i].Priority() < p.middlewares[j].Priority()
	})
	p.sorted = true
}

// snapshot returns a snapshot of the current middleware list (shallow copy).
// Caller only needs read lock.
func (p *MessagePipeline) snapshot() []MessageMiddleware {
	result := make([]MessageMiddleware, len(p.middlewares))
	copy(result, p.middlewares)
	return result
}

// Run executes the pipeline, returns the built message list.
// Concurrency-safe: takes middleware snapshot first, then executes on snapshot without holding lock.
func (p *MessagePipeline) Run(mc *MessageContext) []llm.ChatMessage {
	p.mu.RLock()
	mws := p.snapshot()
	p.mu.RUnlock()

	for _, mw := range mws {
		if err := mw.Process(mc); err != nil {
			log.WithError(err).WithField("middleware", mw.Name()).Warn("Message middleware failed, skipping")
		}
	}

	return mc.Assemble()
}

// Middlewares returns the middleware list in the current pipeline (snapshot sorted by priority)
func (p *MessagePipeline) Middlewares() []MessageMiddleware {
	p.mu.RLock()
	defer p.mu.RUnlock()
	return p.snapshot()
}
