// Code generated by cmd/rpcgen. DO NOT EDIT.
// To regenerate: go run ./cmd/rpcgen/

package agent

import (
	"context"
	"time"

	"xbot/config"
	llm "xbot/llm"
	"xbot/protocol"
)

// ── Generated Backend RPC methods ──────────────────────────────────────────
// Extracted from backend_impl.go. Do not modify — regenerate with rpcgen.

func (b *Backend) GetSettings(namespace, senderID string) (map[string]string, error) {
	var r map[string]string
	return r, b.call(MethodGetSettings, getSettingsReq{Namespace: namespace, SenderID: senderID}, &r)
}

func (b *Backend) SetSetting(namespace, senderID, key, value string) error {
	return b.call(MethodSetSetting, setSettingReq{Namespace: namespace, SenderID: senderID, Key: key, Value: value}, nil)
}

func (b *Backend) GetDefaultModel() string {
	var r string
	_ = b.call(MethodGetDefaultModel, struct{}{}, &r)
	return r
}

func (b *Backend) GetContextMode() string {
	var r string
	_ = b.call(MethodGetContextMode, struct{}{}, &r)
	return r
}

func (b *Backend) ListModels() []string {
	var r []string
	_ = b.call(MethodListModels, struct{}{}, &r)
	return r
}

func (b *Backend) ListAllModels() []string {
	var r []string
	_ = b.call(MethodListAllModels, struct{}{}, &r)
	return r
}

func (b *Backend) SetModelTiers(cfg config.LLMConfig) error {
	return b.call(MethodSetModelTiers, cfg, nil)
}

func (b *Backend) SetDefaultThinkingMode(mode string) error {
	return b.call(MethodSetDefaultThinkingMode, setDefaultThinkingModeReq{Mode: mode}, nil)
}

func (b *Backend) SetModelContexts(contexts map[string]int) error {
	return b.call(MethodSetModelContexts, contexts, nil)
}

func (b *Backend) SetGlobalMaxTokens(maxTokens int) error {
	return b.call(MethodSetGlobalMaxTokens, setGlobalMaxTokensReq{MaxTokens: maxTokens}, nil)
}

func (b *Backend) SetRetryConfig(cfg llm.RetryConfig) error {
	return b.call(MethodSetRetryConfig, cfg, nil)
}

func (b *Backend) SetChatLLM(chatID string, provider string, llmCfg config.LLMConfig) error {
	return b.call(MethodSetChatLLM, setChatLLMReq{
		ChatID:   chatID,
		Provider: provider,
		Config:   llmCfg,
	}, nil)
}

func (b *Backend) ClearProxyLLM(senderID string) {
	b.callVoid(MethodClearProxyLLM, clearProxyLLMReq{SenderID: senderID})
}

func (b *Backend) GetUserMaxContext(senderID string) int {
	var r int
	_ = b.call(MethodGetUserMaxContext, getUserMaxContextReq{SenderID: senderID}, &r)
	return r
}

func (b *Backend) SetUserMaxContext(senderID string, maxContext int) error {
	return b.call(MethodSetUserMaxContext, setUserMaxContextReq{SenderID: senderID, MaxContext: maxContext}, nil)
}

func (b *Backend) GetUserMaxOutputTokens(senderID string) int {
	var r int
	_ = b.call(MethodGetUserMaxOutputTokens, getUserMaxOutputTokensReq{SenderID: senderID}, &r)
	return r
}

func (b *Backend) SetUserMaxOutputTokens(senderID string, maxTokens int) error {
	return b.call(MethodSetUserMaxOutputTokens, setUserMaxOutputTokensReq{SenderID: senderID, MaxTokens: maxTokens}, nil)
}

func (b *Backend) GetUserThinkingMode(senderID string) string {
	var r string
	_ = b.call(MethodGetUserThinkingMode, getUserThinkingModeReq{SenderID: senderID}, &r)
	return r
}

func (b *Backend) SetUserThinkingMode(senderID string, mode string) error {
	return b.call(MethodSetUserThinkingMode, setUserThinkingModeReq{SenderID: senderID, Mode: mode}, nil)
}

func (b *Backend) GetLLMConcurrency(senderID string) int {
	var r int
	_ = b.call(MethodGetLLMConcurrency, getLLMConcurrencyReq{SenderID: senderID}, &r)
	return r
}

func (b *Backend) SetLLMConcurrency(senderID string, personal int) error {
	return b.call(MethodSetLLMConcurrency, setLLMConcurrencyReq{SenderID: senderID, Personal: personal}, nil)
}

func (b *Backend) SetUserModel(senderID, model string) error {
	return b.call(MethodSetUserModel, setUserModelReq{SenderID: senderID, Model: model}, nil)
}

func (b *Backend) SwitchModel(senderID, model, chatID string) error {
	return b.call(MethodSwitchModel, switchModelReq{SenderID: senderID, Model: model, ChatID: chatID}, nil)
}

func (b *Backend) SetMaxIterations(n int) {
	b.callVoid(MethodSetMaxIterations, setMaxIterationsReq{N: n})
}

func (b *Backend) SetMaxConcurrency(n int) {
	b.callVoid(MethodSetMaxConcurrency, setMaxConcurrencyReq{N: n})
}

func (b *Backend) SetCompressionThreshold(f float64) {
	b.callVoid(MethodSetCompressionThreshold, setCompressionThresholdReq{Threshold: f})
}

func (b *Backend) ResetTokenState() { b.callVoid(MethodResetTokenState, struct{}{}) }

// GetEffectiveMaxContext returns the effective max context for a user/session.
// Via RPC — works for both local and remote modes.
func (b *Backend) GetEffectiveMaxContext(senderID, chatID string) int {
	var r int
	_ = b.call(MethodGetEffectiveMaxContext, getEffectiveMaxContextReq{SenderID: senderID, ChatID: chatID}, &r)
	return r
}

// ClearPerChatMaxContext clears the per-session max_context override.
// Via RPC — works for both local and remote modes.
func (b *Backend) ClearPerChatMaxContext(chatID string) {
	b.callVoid(MethodClearPerChatMaxContext, clearPerChatMaxContextReq{ChatID: chatID})
}

func (b *Backend) CleanupCompletedBgTasks(sessionKey string) {
	b.callVoid(MethodCleanupCompletedBgTasks, cleanupCompletedBgTasksReq{SessionKey: sessionKey})
}

func (b *Backend) SetContextMode(mode string) error {
	return b.call(MethodSetContextMode, setContextModeReq{Mode: mode}, nil)
}

func (b *Backend) SetCWD(ch, chatID, dir string) error {
	return b.call(MethodSetCWD, setCWDReq{Channel: ch, ChatID: chatID, Dir: dir}, nil)
}

func (b *Backend) GetUserTokenUsage(senderID string) (map[string]any, error) {
	var r map[string]any
	return r, b.call(MethodGetUserTokenUsage, getUserTokenUsageReq{SenderID: senderID}, &r)
}

func (b *Backend) GetDailyTokenUsage(senderID string, days int) ([]map[string]any, error) {
	var r []map[string]any
	return r, b.call(MethodGetDailyTokenUsage, getDailyTokenUsageReq{SenderID: senderID, Days: days}, &r)
}

func (b *Backend) GetBgTaskCount(sessionKey string) int {
	var r int
	_ = b.call(MethodGetBgTaskCount, getBgTaskCountReq{SessionKey: sessionKey}, &r)
	return r
}

func (b *Backend) ListBgTasks(sessionKey string) ([]BgTaskJSON, error) {
	var r []BgTaskJSON
	return r, b.call(MethodListBgTasks, listBgTasksReq{SessionKey: sessionKey}, &r)
}

func (b *Backend) KillBgTask(taskID string) error {
	return b.call(MethodKillBgTask, killBgTaskReq{TaskID: taskID}, nil)
}

func (b *Backend) ListTenants() ([]TenantInfo, error) {
	var r []TenantInfo
	return r, b.call(MethodListTenants, struct{}{}, &r)
}

func (b *Backend) ListSubscriptions(senderID string) ([]protocol.Subscription, error) {
	var r []protocol.Subscription
	return r, b.call(MethodListSubscriptions, listSubscriptionsReq{SenderID: senderID}, &r)
}

func (b *Backend) GetDefaultSubscription(senderID string) (*protocol.Subscription, error) {
	var r *protocol.Subscription
	return r, b.call(MethodGetDefaultSubscription, getDefaultSubscriptionReq{SenderID: senderID}, &r)
}

func (b *Backend) RemoveSubscription(id string) error {
	return b.call(MethodRemoveSubscription, removeSubscriptionReq{ID: id}, nil)
}

func (b *Backend) SetDefaultSubscription(id string, chatID string) error {
	return b.call(MethodSetDefaultSubscription, setDefaultSubscriptionReq{ID: id, ChatID: chatID}, nil)
}

func (b *Backend) UpdatePerModelConfig(id, model string, pmc protocol.PerModelConfig) error {
	return b.call(MethodUpdatePerModelConfig, updatePerModelConfigReq{
		ID: id, Model: model, Config: pmc,
	}, nil)
}

func (b *Backend) SetSubscriptionModel(id, model string) error {
	return b.call(MethodSetSubscriptionModel, setSubscriptionModelReq{ID: id, Model: model}, nil)
}

func (b *Backend) RenameSubscription(id, name string) error {
	return b.call(MethodRenameSubscription, renameSubscriptionReq{ID: id, Name: name}, nil)
}

func (b *Backend) ClearMemory(ctx context.Context, channelName, chatID, targetType, senderID string) error {
	return b.call(MethodClearMemory, clearMemoryReq{
		Channel: channelName, ChatID: chatID, TargetType: targetType, SenderID: senderID,
	}, nil)
}

func (b *Backend) GetMemoryStats(ctx context.Context, ch, chatID, senderID string) map[string]string {
	var r map[string]string
	_ = b.call(MethodGetMemoryStats, getMemoryStatsReq{Channel: ch, ChatID: chatID, SenderID: senderID}, &r)
	return r
}

func (b *Backend) GetHistory(channelName, chatID string) ([]protocol.HistoryMessage, error) {
	var r []protocol.HistoryMessage
	return r, b.call(MethodGetHistory, getHistoryReq{Channel: channelName, ChatID: chatID}, &r)
}

func (b *Backend) TrimHistory(ch, chatID string, cutoff time.Time) error {
	return b.call(MethodTrimHistory, trimHistoryReq{Channel: ch, ChatID: chatID, Cutoff: cutoff.Unix()}, nil)
}

func (b *Backend) CountInteractiveSessions(channelName, chatID string) int {
	var r int
	_ = b.call(MethodCountInteractiveSessions, countInteractiveSessionsReq{ChannelName: channelName, ChatID: chatID}, &r)
	return r
}

func (b *Backend) ListInteractiveSessions(channelName, chatID string) []InteractiveSessionInfo {
	var r []InteractiveSessionInfo
	_ = b.call(MethodListInteractiveSessions, listInteractiveSessionsReq{ChannelName: channelName, ChatID: chatID}, &r)
	return r
}

func (b *Backend) InspectInteractiveSession(ctx context.Context, roleName, channelName, chatID, instance string, tailCount int) (string, error) {
	var r string
	return r, b.call(MethodInspectInteractiveSession, inspectInteractiveSessionReq{
		RoleName: roleName, ChannelName: channelName,
		ChatID: chatID, Instance: instance, TailCount: tailCount,
	}, &r)
}

func (b *Backend) IsProcessing(ch, chatID string) bool {
	var r bool
	_ = b.call(MethodIsProcessing, isProcessingReq{Channel: ch, ChatID: chatID}, &r)
	return r
}

func (b *Backend) GetActiveProgress(ch, chatID string) *protocol.ProgressEvent {
	var r *protocol.ProgressEvent
	_ = b.call(MethodGetActiveProgress, getActiveProgressReq{Channel: ch, ChatID: chatID}, &r)
	return r
}

func (b *Backend) GetTodos(ch, chatID string) []protocol.TodoItem {
	var r []protocol.TodoItem
	_ = b.call(MethodGetTodos, getTodosReq{Channel: ch, ChatID: chatID}, &r)
	return r
}

func (b *Backend) GetChannelConfigs() (map[string]map[string]string, error) {
	var r map[string]map[string]string
	return r, b.call(MethodGetChannelConfig, struct{}{}, &r)
}

func (b *Backend) SetChannelConfig(channel string, values map[string]string) error {
	return b.call(MethodSetChannelConfig, setChannelConfigReq{Channel: channel, Values: values}, nil)
}
