/**
 * Icon — lucide-react subset exposed to LLM-generated GenUI.
 * Keeps common icons available; the full set is importable via lucide-react
 * if bundled, but exposing a curated subset keeps compile scope tiny.
 */
import React from 'react'
import {
  AlertCircle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  BarChart2,
  Bell,
  BookOpen,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Copy,
  Database,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  GitBranch,
  Heart,
  Home,
  Info,
  Link2,
  List,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  MoreHorizontal,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Star,
  StopCircle,
  Sun,
  Tag,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react'

export interface IconProps {
  name?: string
  size?: number
  className?: string
  [key: string]: unknown
}

const registry: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  alert: AlertCircle,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'bar-chart': BarChart2,
  bell: Bell,
  book: BookOpen,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  clock: Clock,
  copy: Copy,
  database: Database,
  download: Download,
  edit: Edit3,
  external: ExternalLink,
  eye: Eye,
  file: FileText,
  filter: Filter,
  github: GitBranch,
  heart: Heart,
  home: Home,
  info: Info,
  link: Link2,
  list: List,
  'loader': Loader2,
  lock: Lock,
  mail: Mail,
  map: MapPin,
  menu: Menu,
  message: MessageSquare,
  more: MoreHorizontal,
  pause: Pause,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  stop: StopCircle,
  sun: Sun,
  tag: Tag,
  trash: Trash2,
  'trend-down': TrendingDown,
  'trend-up': TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
}

// Re-export the raw icons too (for direct use in LLM code).
export {
  AlertCircle,
  ArrowUp,
  BarChart2,
  Bell,
  Check,
  CheckCircle2,
  Clock,
  Copy,
  Database,
  Edit3,
  ExternalLink,
  Eye,
  FileText,
  GitBranch,
  Heart,
  Info,
  Link2,
  Loader2,
  Mail,
  MessageSquare,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Star,
  Sun,
  Trash2,
  TrendingUp,
  TrendingDown,
  User,
  Users,
  X,
  Zap,
}

export function Icon({ name, size = 16, className, ...rest }: IconProps) {
  const Comp = name ? registry[name] : null
  if (!Comp) return null
  return <Comp size={size} className={className} {...(rest as Record<string, unknown>)} />
}
